/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/corporate': typeof CorporateRoute
  '/recipes': typeof RecipesRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/corporate': typeof CorporateRoute
  '/recipes': typeof RecipesRoute
  '/shop': typeof ShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/corporate': typeof CorporateRoute
  '/recipes': typeof RecipesRoute
  '/shop': typeof ShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/academy' | '/corporate' | '/recipes' | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/academy' | '/corporate' | '/recipes' | '/shop'
  id: '__root__' | '/' | '/academy' | '/corporate' | '/recipes' | '/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  CorporateRoute: typeof CorporateRoute
  RecipesRoute: typeof RecipesRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  CorporateRoute: CorporateRoute,
  RecipesRoute: RecipesRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
